#!/usr/bin/env bash
## BSPWM config file for Archcraft

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Current theme ---------------------------------------------#

## Load current theme files to get colors for bspwm
source "$BSPDIR"/themes/current.bash

## Get the wallpaper from theme file
CURRENT_WALLPAPER="$wallpaper"

## Get the colors from theme file
FOREGROUND="$foreground"
BACKGROUND="$background"
CURSOR="$cursor"
BLACK="$color0"
RED="$color1"
GREEN="$color2"
YELLOW="$color3"
BLUE="$color4"
MAGENTA="$color5"
CYAN="$color6"
WHITE="$color7"
ALTBLACK="$color8"
ALTRED="$color9"
ALTGREEN="$color10"
ALTYELLOW="$color11"
ALTBLUE="$color12"
ALTMAGENTA="$color13"
ALTCYAN="$color14"
ALTWHITE="$color15"

## Configurations --------------------------------------------#
# bspc monitor eDP-1 -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
# extra icons --                                    
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		# bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		# bspc monitor ${monitor} -n "$name" -d '① ' '② ' '③ ' '④ ' '⑤ ' '⑥ ' '⑦ ' '⑧ '
		bspc monitor ${monitor} -n "$name" -d '❶ ' '❷ ' '❸ ' '❹ ' '❺ ' '❻ ' '❼ ' '❽ '
		# bspc monitor ${monitor} -n "$name" -d '' '爵' '' '' '龎' '' '嗢' ''
		let name++
	done
}
workspaces

bspc config border_width 0
bspc config border_radius 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

# Move Windows using mouse
bspc subscribe pointer_action &
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# preselectd area gets more preference than rules
#bspc rule -a '*' node='focused.!automatic'

# 1 > terminal
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a google-chrome desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on

# 3 > files
declare -a files=(Pcmanfm Thunar)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 4 > code
declare -a code=(Geany Code android-studio jetbrains-studio)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# 5 > office and docs
declare -a office=(zoom Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

# 6 > Communication
declare -a comm=(Thunderbird TelegramDesktop qBittorrent discord Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

# 7 > media
declare -a media=(vlc Spotify Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10 obs)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' follow=on focus=on; done

# 8 > settings
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(rdesktop filelight timeshift Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Xfce4-taskmanager gnome-system-monitor Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# special rules
declare -a floating=(alacritty-float Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Start clipboard daemon
greenclip deamon &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr
# xinput --disable "ETPS/2 Elantech Touchpad"

# Disable "+" key 
xmodmap -e "keycode  86 = "

# Restore wallpaper
# bash $HOME/.fehbg
# feh --no-fehbg --bg-scale "$CURRENT_WALLPAPER" &
# feh --no-fehbg --bg-center "$CURRENT_WALLPAPER" &
feh --no-fehbg --bg-fill "$CURRENT_WALLPAPER" &

# BetterLockScreen 
betterlockscreen -u "$CURRENT_WALLPAPER" &

# Start mpd
# exec mpd &

# Start bspwm scripts
bspcolors &
bspbar --minimal &
bspcomp &
bspdunst &
# bspfloat &

