# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/Wallpapers/Fk2aJYDXgAECgZd.jpg'

# Special
background='#0d0a09'
foreground='#cbd4d8'
cursor='#cbd4d8'

# Colors
color0='#0d0a09'
color1='#4D4C50'
color2='#655F60'
color3='#986045'
color4='#8B8474'
color5='#7095A7'
color6='#97A7B0'
color7='#cbd4d8'
color8='#8e9497'
color9='#4D4C50'
color10='#655F60'
color11='#986045'
color12='#8B8474'
color13='#7095A7'
color14='#97A7B0'
color15='#cbd4d8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
