# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/Wallpapers/Swish-by-Michael-Boegl-scaled.jpg'

# Special
background='#0E1413'
foreground='#e3e9ea'
cursor='#e3e9ea'

# Colors
color0='#0E1413'
color1='#546460'
color2='#797E6F'
color3='#738D8B'
color4='#96ACAB'
color5='#ADBFBF'
color6='#B5C8CA'
color7='#e3e9ea'
color8='#9ea3a3'
color9='#546460'
color10='#797E6F'
color11='#738D8B'
color12='#96ACAB'
color13='#ADBFBF'
color14='#B5C8CA'
color15='#e3e9ea'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
