# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/dynamic-wallpaper/images/forest/23.jpg'

# Special
background='#040B10'
foreground='#a1c3e1'
cursor='#a1c3e1'

# Colors
color0='#040B10'
color1='#164DAA'
color2='#225DB1'
color3='#4478B0'
color4='#3276C5'
color5='#4982BA'
color6='#3D83CB'
color7='#a1c3e1'
color8='#70889d'
color9='#164DAA'
color10='#225DB1'
color11='#4478B0'
color12='#3276C5'
color13='#4982BA'
color14='#3D83CB'
color15='#a1c3e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
